'use client';
import { useEffect } from 'react';
const HONEYPOTS=new Set(['websiteConfirm','website_confirm','website_url','company_homepage']);
function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'action'}
export function AcrClient(){useEffect(()=>{
  const labelCtas=()=>{const used=new Set<string>();document.querySelectorAll<HTMLElement>('a[href],button:not([type="submit"]),[role="button"]').forEach((el)=>{if(el.closest('form')||el.id.startsWith('cta-')){if(el.id)used.add(el.id);return}const scope=el.closest('header')?'global-header':el.closest('footer')?'global-footer':slug(location.pathname==='/'?'home':location.pathname);const raw=slug(el.textContent||el.getAttribute('aria-label')||el.getAttribute('href')||'action');let id=`cta-${scope}-${raw}`,n=2;while(used.has(id)||document.getElementById(id))id=`cta-${scope}-${raw}-${n++}`;el.id=id;used.add(id)});document.querySelectorAll<HTMLIFrameElement>('iframe[src*="oncehub.com"],iframe[src*="scheduleonce.com"]').forEach(frame=>{const wrapper=frame.parentElement;if(wrapper&&!wrapper.dataset.acrTrack)wrapper.dataset.acrTrack='contact-booking-iframe'})};
  labelCtas();const observer=new MutationObserver(labelCtas);observer.observe(document.documentElement,{childList:true,subtree:true});
  const submit=async(event:SubmitEvent)=>{const form=event.target;if(!(form instanceof HTMLFormElement)||form.dataset.acrHandled==='1')return;const action=new URL(form.action||location.href,location.href);if((form.method||'get').toLowerCase()!=='post'||action.origin!==location.origin||action.pathname!=='/api/contact')return;event.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);for(const key of HONEYPOTS)if(String(data.get(key)||''))return;form.dataset.acrHandled='1';const controls=[...form.querySelectorAll<HTMLButtonElement|HTMLInputElement>('[type="submit"]')];controls.forEach(x=>{x.disabled=true;x.setAttribute('aria-busy','true')});try{const response=await fetch(action,{method:'POST',body:data,headers:{Accept:'text/html'}});if(!response.ok)throw new Error('site lead backend rejected submission');const payload:Record<string,string>={};for(const [key,value] of data.entries())if(typeof value==='string'&&!HONEYPOTS.has(key))payload[key]=value;const name=payload.name||`${payload.firstName||''} ${payload.lastName||''}`.trim();for(let i=0;i<20&&!window.acrTracker;i++)await new Promise(r=>setTimeout(r,100));window.acrTracker?.trackLead({...payload,name,email:payload.email||'',phone:payload.phone||'',message:payload.message||payload.needs||payload.details||'',source:'contact-page-intake',formId:form.id||'contact-form',pageUrl:location.href});const target=new URL(response.url||'/thank-you',location.href);location.assign(target.origin===location.origin?target.href:'/thank-you')}catch(error){console.error('[contact-form] submission failed',error);form.dataset.acrHandled='0';controls.forEach(x=>{x.disabled=false;x.removeAttribute('aria-busy')});alert('We could not send your request. Please try again.')}};
  document.addEventListener('submit',submit,true);return()=>{observer.disconnect();document.removeEventListener('submit',submit,true)}
},[]);return null}
