import * as data from './data';
import { Header, Footer, JsonLd } from './components';
const d=data as any, site=d.site||{}, services=(d.services||[]).slice(0,4), posts=(d.blogPosts||[]).slice(0,4), stats=(d.stats||[]).slice(0,3), offer=d.staffingOffer||{};
const title=(x:any)=>typeof x==='string'?x:(x.title||x.name||x.label||x.question||'Design pod');
const text=(x:any)=>typeof x==='string'?x:(x.desc||x.excerpt||x.note||x.body||'Design production with brief, QA, revision, and launch handoff.');
const slug=(x:any)=>(x.slug||title(x).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));
export default function Home(){const schema={'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:`https://${site.domain}`};return <><Header/><main className="fancy"><JsonLd data={schema}/>
<section className="hero"><div className="container hero-grid"><div className="copy"><p className="eyebrow">Website production pod</p><h1>Ship better pages without chasing every revision.</h1><p className="lead">Hire design support for briefs, page updates, mobile QA, SEO fields, forms, revisions, and handoff cleanup.</p><div className="actions"><a className="btn primary" href="/contact">Request design staffing plan</a><a className="btn secondary" href="#workflow">See QA workflow</a></div><p className="risk">Built for steady production, not one-off pretty drafts.</p></div><div className="workflow-card"><div className="browser-top"><span></span><span></span><span></span><b>homepage-v2.fig</b></div><div className="canvas"><div className="sticky one">brief approved</div><div className="frame"><img src={site.heroImage||site.serviceImage||'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80'} alt={site.alt||'website design outsource workflow'}/></div><div className="sticky two">mobile QA</div><div className="sticky three">SEO fields</div></div></div></div></section>
<section className="container stat-bubbles">{stats.map((s:any,i:number)=><article key={i}><b>{s.value}</b><span>{s.label}</span><p>{s.note}</p></article>)}</section>
<section className="container section" id="workflow"><div className="section-head"><p className="eyebrow">Production pods</p><h2>Give each page a brief, owner, QA pass, and handoff trail.</h2></div><div className="pod-grid">{services.map((s:any,i:number)=>{const podTitles=['Page Production Support','Website QA Support','CMS + Admin Updates','Reporting + Handoff QA']; return <a href={`/services/${slug(s)}`} key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{podTitles[i]||title(s)}</h3><p>{text(s)}</p><b>See pod →</b></a>})}</div></section>
<section className="brief"><div className="container brief-grid"><div><p className="eyebrow">Revision-proof process</p><h2>Design outsourcing fails when the feedback loop is vague.</h2><p>{offer.promise||site.angle}</p></div><div className="checklist">{(offer.included||['brief planning','candidate matching','QA scorecards','managed support']).slice(0,4).map((x:string,i:number)=><article key={i}><span>{i+1}</span><p>{x}</p></article>)}</div></div></section>
<section className="container section articles"><div className="section-head"><p className="eyebrow">Buyer notes</p><h2>Questions to ask before outsourcing design.</h2></div><div>{posts.map((p:any,i:number)=><a href={`/blog/${p.slug}`} key={i}><span>{p.minutes||7} min</span><strong>{title(p)}</strong><p>{text(p)}</p></a>)}</div></section>
<section className="container final"><div><p className="eyebrow">Next brief</p><h2>Send the design workload. Get the staffing plan.</h2></div><a className="btn primary" href="/contact">Request staffing plan</a></section>
</main><Footer/></>}
