import * as data from './data';
import { Header, Footer, JsonLd } from './components';
const d=data as any, site=d.site||{}, services=(d.services||[]).slice(0,6), posts=(d.blogPosts||[]).slice(0,4), stats=(d.stats||[]).slice(0,3), offer=d.staffingOffer||{};
const title=(x:any)=>typeof x==='string'?x:(x.title||x.name||x.label||x.question||'Design support');
const text=(x:any)=>typeof x==='string'?x:(x.desc||x.excerpt||x.note||x.body||'Design production with briefs, QA, revisions, and handoff rules.');
const slug=(x:any)=>(x.slug||title(x).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));
export default function Home(){const schema={'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:`https://${site.domain}`};return <><Header/><main className="studio"><JsonLd data={schema}/>
<section className="studio-hero"><div className="container hero-mosaic"><div><p className="eyebrow">Creative studio pod</p><h1>Outsource website design with a brief, a pod, and a QA finish line.</h1><p className="lead">A design-production guide for teams that need pages, updates, revisions, SEO handoff, and clean ownership of source files.</p><div className="hero-actions"><a className="btn primary" href="/contact">Request staffing plan</a><a className="btn secondary" href="#services">View pod roles</a></div></div><div className="mosaic"><div className="design-board" aria-label="website design QA board"><div className="browser-bar"><i/><i/><i/></div><div className="wire"><span/><span/><span/></div><div className="checklist"><b>Launch QA</b><p>Mobile ✓ Forms ✓ SEO fields ✓</p></div></div><article><span>Brief</span><b>Page goal + examples</b></article><article><span>QA</span><b>Mobile, forms, SEO fields</b></article></div></div></section>
<section className="container stats-strip">{stats.map((s:any,i:number)=><article key={i}><span>{s.label}</span><b>{s.value}</b><p>{s.note}</p></article>)}</section>
<section className="container section" id="services"><div className="section-head"><p className="eyebrow">Production pods</p><h2>Different work needs different design support.</h2><p>Pick the pod by work type: page production, admin support, customer updates, reporting, and QA.</p></div><div className="pod-grid">{services.map((s:any,i:number)=><a href={`/services/${slug(s)}`} key={i}><img src={i%2===0?(site.serviceImage||site.heroImage):(site.heroImage||site.serviceImage)} alt=""/><div><span>{String(i+1).padStart(2,'0')}</span><h3>{title(s)}</h3><p>{text(s)}</p><b>See handoff →</b></div></a>)}</div></section>
<section className="brief-band"><div className="container brief-grid"><div><p className="eyebrow light">Better handoff</p><h2>Pretty drafts are not enough. The handoff has to survive revision week.</h2><p>{offer.promise||site.angle}</p></div><div className="brief-list">{(offer.included||['brief planning','candidate matching','QA scorecards','managed support']).slice(0,4).map((x:string,i:number)=><article key={i}><span>{i+1}</span><p>{x}</p></article>)}</div></div></section>
<section className="container section resources"><div className="section-head"><p className="eyebrow">Design buyer notes</p><h2>Ask sharper questions before hiring.</h2></div><div className="article-wall">{posts.map((p:any,i:number)=><a href={`/blog/${p.slug}`} key={i}><span>{p.minutes||7} min</span><strong>{title(p)}</strong><p>{text(p)}</p></a>)}</div></section>
<section className="container studio-cta"><div><p className="eyebrow light">Next brief</p><h2>Send the design workload. Get a staffing plan.</h2></div><a className="btn primary" href="/contact">Request staffing plan</a></section>
</main><Footer/></>}
